Repository aforero31/MISW4203_PR_MOVILES, pull requests merged in 2022-11, with the labels that each got.

#43 Add: Main menu and menu defaultUser
  .idea/vcs.xml
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/MenuCollectorFragment.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/MenuUsuarioFragment.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/UsersFragment.kt
  app/src/main/res/layout/fragment_menu_collector.xml
  app/src/main/res/layout/menu_usuario_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: HU01

#44 Modelo para Album + Requests para Album y Artistas
  .gitignore
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/models/Musician.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/network/NetworkServiceAdapter.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/repositories/AlbumRepository.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/AlbumFragment.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/adapters/AlbumsAdapter.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/viewmodels/AlbumViewModel.kt
  app/src/main/res/layout/album_fragment.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/values/strings.xml
Labels: HU01

#46 Creacion de ViewModel Artistas
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/MusicianFragment.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/adapters/MusiciansAdapter.kt
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/viewmodels/MusicianViewModel.kt
  app/src/main/res/layout/musician_fragment.xml
  app/src/main/res/layout/musician_item.xml
Labels: enhancement

#50 Feature/musicians list view
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/moviles_vinils_app_grupo_32/ui/MenuUsuarioFragment.kt
  app/src/main/res/font/roboto_black.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/musician_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: HU03

#52 Feature/test
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/androidTest/java/com/example/moviles_vinils_app_grupo_32/ui/ExploracionTest.java
  app/src/androidTest/java/com/example/moviles_vinils_app_grupo_32/ui/MainActivityTest.kt
  app/src/androidTest/java/com/example/moviles_vinils_app_grupo_32/ui/MainActivityTest2.kt
  app/src/androidTest/java/com/example/moviles_vinils_app_grupo_32/ui/MainActivityTest3.kt
  app/src/androidTest/java/com/example/moviles_vinils_app_grupo_32/ui/Test1.java
Labels: enhancement, HU01
